// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const attachments = sqliteTable(
  "attachments",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id").notNull(),
    filename: text("filename").notNull(),
    mimeType: text("mime_type"),
    sizeBytes: integer("size_bytes", { mode: "number" }),
    storageKey: text("storage_key").notNull(),
    storageUrl: text("storage_url"),
    uploadedBy: uuid("uploaded_by"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
