// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, inet, nowDefault } from "../types.js";

export const auditLogs = sqliteTable(
  "audit_logs",
  {
    id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
    tenantId: uuid("tenant_id").notNull(),
    actorId: uuid("actor_id"),
    actorName: text("actor_name"),
    module: text("module").notNull(),
    action: text("action").notNull(),
    entityType: text("entity_type"),
    entityId: uuid("entity_id"),
    detail: text("detail"),
    beforeSnapshot: jsonb("before_snapshot"),
    afterSnapshot: jsonb("after_snapshot"),
    ipAddress: inet("ip_address"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
