// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text, primaryKey } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, numeric, nowDefault, randomUuid } from "../types.js";

export const cashboxDailyBalances = sqliteTable(
  "cashbox_daily_balances",
  {
    tenantId: uuid("tenant_id").notNull(),
    currency: text("currency").notNull(),
    balanceDate: date("balance_date").notNull(),
    closingBalance: numeric("closing_balance", { precision: 14, scale: 2 }).notNull().default(0),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
  (t) => [primaryKey({ columns: [t.tenantId, t.currency, t.balanceDate] })],
);

export const cashboxSessions = sqliteTable(
  "cashbox_sessions",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    openingBalance: numeric("opening_balance", { precision: 14, scale: 2 }).notNull().default(0),
    openingDate: date("opening_date").notNull(),
    currency: text("currency").notNull().default("SYP"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);

export const dayCloses = sqliteTable(
  "day_closes",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    date: date("date").notNull(),
    openingBalance: numeric("opening_balance", { precision: 14, scale: 2 }).notNull(),
    totalIn: numeric("total_in", { precision: 14, scale: 2 }).notNull(),
    totalOut: numeric("total_out", { precision: 14, scale: 2 }).notNull(),
    expected: numeric("expected", { precision: 14, scale: 2 }).notNull(),
    counted: numeric("counted", { precision: 14, scale: 2 }).notNull(),
    difference: numeric("difference", { precision: 14, scale: 2 }).notNull(),
    currency: text("currency").notNull().default("SYP"),
    closedAt: timestamptz("closed_at").notNull().$defaultFn(nowDefault),
    closedBy: uuid("closed_by"),
  },
);

export const manualMovements = sqliteTable(
  "manual_movements",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    date: date("date").notNull(),
    type: text("type").notNull(),
    direction: text("direction").notNull(),
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
    currency: text("currency").notNull().default("SYP"),
    description: text("description"),
    notesInternal: text("notes_internal"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    createdBy: uuid("created_by"),
    clientOperationId: uuid("client_operation_id"),
  },
);
