// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const colors = sqliteTable(
  "colors",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    fabricId: uuid("fabric_id").notNull(),
    name: text("name").notNull(),
    code: text("code"),
    hex: text("hex"),
    imageUrl: text("image_url"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
