// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, date, decimalString, nowDefault, randomUuid } from "../types.js";

export const companyProfiles = sqliteTable(
  "company_profiles",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    name: text("name").notNull(),
    commercialReg: text("commercial_reg"),
    taxNumber: text("tax_number"),
    address: text("address"),
    city: text("city"),
    country: text("country"),
    phone: text("phone"),
    email: text("email"),
    logoPath: text("logo_path"),
    currency: text("currency").notNull().default("SYP"),
    language: text("language").notNull().default("ar"),
    fiscalYearStart: date("fiscal_year_start"),
    defaultTaxRate: decimalString("default_tax_rate", { precision: 5, scale: 4 }).notNull().default("0.0000"),
    customization: jsonb("customization").default({}),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
