// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const deviceRegistrations = sqliteTable(
  "device_registrations",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    licenseId: uuid("license_id").notNull(),
    tenantId: uuid("tenant_id").notNull(),
    deviceId: uuid("device_id").notNull(),
    userId: uuid("user_id"),
    deviceFingerprint: text("device_fingerprint").notNull(),
    deviceFingerprintVersion: integer("device_fingerprint_version", { mode: "number" }).notNull().default(1),
    platform: text("platform").notNull(),
    name: text("name"),
    signedToken: text("signed_token"),
    signedTokenExpiresAt: timestamptz("signed_token_expires_at"),
    lastSeenAt: timestamptz("last_seen_at").notNull().$defaultFn(nowDefault),
    revokedAt: timestamptz("revoked_at"),
    revokeReason: text("revoke_reason"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
