// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const documentNumberBlocks = sqliteTable(
  "document_number_blocks",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    syncDeviceId: uuid("sync_device_id").notNull(),
    entityType: text("entity_type").notNull(),
    year: integer("year", { mode: "number" }).notNull(),
    prefix: text("prefix").notNull(),
    startNumber: integer("start_number", { mode: "number" }).notNull(),
    endNumber: integer("end_number", { mode: "number" }).notNull(),
    nextNumber: integer("next_number", { mode: "number" }).notNull(),
    status: text("status").notNull().default("active"),
    claimedAt: timestamptz("claimed_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
    reclaimedAt: timestamptz("reclaimed_at"),
  },
);
