// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, randomUuid } from "../types.js";

export const documentSequences = sqliteTable(
  "document_sequences",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    entityType: text("entity_type").notNull(),
    prefix: text("prefix"),
    lastNumber: integer("last_number", { mode: "number" }).notNull().default(0),
  },
);
