// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, boolean, date, numeric, nowDefault, randomUuid } from "../types.js";

export const expenses = sqliteTable(
  "expenses",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    number: text("number").notNull(),
    category: text("category").notNull(),
    description: text("description").notNull(),
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
    currency: text("currency").notNull().default("SYP"),
    date: date("date").notNull(),
    method: text("method").notNull(),
    paidFromCashbox: boolean("paid_from_cashbox").notNull().default(true),
    status: text("status").notNull().default("active"),
    notesPrint: text("notes_print"),
    notesInternal: text("notes_internal"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    createdBy: uuid("created_by"),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
    cancelledAt: timestamptz("cancelled_at"),
    cancelledBy: uuid("cancelled_by"),
    clientOperationId: uuid("client_operation_id"),
  },
);
