// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, decimalString, nowDefault, randomUuid } from "../types.js";

export const fabrics = sqliteTable(
  "fabrics",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    name: text("name").notNull(),
    category: text("category"),
    minStockKg: decimalString("min_stock_kg", { precision: 12, scale: 2 }).default("0"),
    unit: text("unit"),
    notes: text("notes"),
    imageUrl: text("image_url"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    createdBy: uuid("created_by"),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
