// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, date, nowDefault, randomUuid } from "../types.js";

export const financialYears = sqliteTable(
  "financial_years",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    year: integer("year", { mode: "number" }).notNull(),
    status: text("status").notNull().default("open"),
    periodStart: date("period_start").notNull(),
    periodEnd: date("period_end").notNull(),
    closedAt: timestamptz("closed_at"),
    closedBy: uuid("closed_by"),
    reopenedAt: timestamptz("reopened_at"),
    reopenedBy: uuid("reopened_by"),
    reopenReason: text("reopen_reason"),
    closingCashbox: jsonb("closing_cashbox").notNull().default({}),
    closingInventoryValue: jsonb("closing_inventory_value").notNull().default({}),
    notes: text("notes"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
