// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, nowDefault } from "../types.js";

export const idempotencyKeys = sqliteTable(
  "idempotency_keys",
  {
    id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
    tenantId: uuid("tenant_id").notNull(),
    method: text("method").notNull(),
    path: text("path").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    statusCode: integer("status_code", { mode: "number" }).notNull(),
    responseBody: jsonb("response_body"),
    contentType: text("content_type").notNull().default("application/json; charset=utf-8"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    expiresAt: timestamptz("expires_at").notNull(),
  },
);
