// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, numeric, nowDefault, randomUuid } from "../types.js";

export const inventoryCounts = sqliteTable(
  "inventory_counts",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    year: integer("year", { mode: "number" }).notNull(),
    rollId: uuid("roll_id").notNull(),
    bookKg: numeric("book_kg", { precision: 14, scale: 2 }).notNull(),
    bookPieces: integer("book_pieces", { mode: "number" }).notNull().default(0),
    countedKg: numeric("counted_kg", { precision: 14, scale: 2 }),
    countedPieces: integer("counted_pieces", { mode: "number" }),
    diffKg: numeric("diff_kg", { precision: 14, scale: 2 }),
    diffPieces: integer("diff_pieces", { mode: "number" }),
    status: text("status").notNull().default("counted"),
    reason: text("reason"),
    countedBy: uuid("counted_by"),
    countedAt: timestamptz("counted_at"),
    approvedBy: uuid("approved_by"),
    approvedAt: timestamptz("approved_at"),
    postedMovementId: uuid("posted_movement_id"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
