// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, nowDefault, randomUuid } from "../types.js";

export const invitationCodes = sqliteTable(
  "invitation_codes",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    licenseId: uuid("license_id"),
    code: text("code").notNull(),
    type: text("type").notNull(),
    expiresAt: timestamptz("expires_at").notNull(),
    revokedAt: timestamptz("revoked_at"),
    useCount: integer("use_count", { mode: "number" }).notNull().default(0),
    metadata: jsonb("metadata").notNull().default({}),
    createdBy: uuid("created_by").notNull(),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
