// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, numeric, decimalString, nowDefault, randomUuid } from "../types.js";

export const invoiceLines = sqliteTable(
  "invoice_lines",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    invoiceId: uuid("invoice_id").notNull(),
    fabricId: uuid("fabric_id").notNull(),
    colorId: uuid("color_id").notNull(),
    rollId: uuid("roll_id").notNull(),
    quantityKg: decimalString("quantity_kg", { precision: 12, scale: 2 }).notNull(),
    pieces: integer("pieces", { mode: "number" }).notNull().default(1),
    pricePerKg: decimalString("price_per_kg", { precision: 12, scale: 2 }).notNull(),
    discountAmount: numeric("discount_amount", { precision: 14, scale: 2 }).notNull().default(0),
    costPerKg: decimalString("cost_per_kg", { precision: 14, scale: 4 }),
    note: text("note"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
