// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, numeric, nowDefault, randomUuid } from "../types.js";

export const invoices = sqliteTable(
  "invoices",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    number: text("number").notNull(),
    reference: text("reference"),
    type: text("type").notNull(),
    date: date("date").notNull(),
    partyId: uuid("party_id").notNull(),
    partyType: text("party_type").notNull(),
    currency: text("currency").notNull().default("SYP"),
    subtotal: numeric("subtotal", { precision: 14, scale: 2 }).notNull().default(0),
    discount: numeric("discount", { precision: 14, scale: 2 }).notNull().default(0),
    tax: numeric("tax", { precision: 14, scale: 2 }).notNull().default(0),
    shipping: numeric("shipping", { precision: 14, scale: 2 }).notNull().default(0),
    total: numeric("total", { precision: 14, scale: 2 }).notNull().default(0),
    paid: numeric("paid", { precision: 14, scale: 2 }).notNull().default(0),
    piecesCount: integer("pieces_count", { mode: "number" }),
    creditApplied: numeric("credit_applied", { precision: 14, scale: 2 }).notNull().default(0),
    paymentMethod: text("payment_method"),
    exchangeRate: numeric("exchange_rate", { precision: 18, scale: 6 }),
    baseTotal: numeric("base_total", { precision: 14, scale: 2 }),
    basePaid: numeric("base_paid", { precision: 14, scale: 2 }),
    notes: text("notes"),
    status: text("status").notNull().default("active"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    createdBy: uuid("created_by"),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
    cancelledAt: timestamptz("cancelled_at"),
    cancelledBy: uuid("cancelled_by"),
    cancellationReferenceId: uuid("cancellation_reference_id"),
    clientOperationId: uuid("client_operation_id"),
  },
);
