// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, numeric, nowDefault } from "../types.js";

export const ledgerEntryArchive = sqliteTable(
  "ledger_entry_archive",
  {
    id: uuid("id").notNull().primaryKey(),
    tenantId: uuid("tenant_id").notNull(),
    partyId: uuid("party_id"),
    date: date("date").notNull(),
    type: text("type").notNull(),
    debit: numeric("debit", { precision: 14, scale: 2 }).default(0),
    credit: numeric("credit", { precision: 14, scale: 2 }).default(0),
    currency: text("currency").notNull().default("SYP"),
    cashImpact: text("cash_impact").notNull().default("none"),
    referenceType: text("reference_type"),
    referenceId: uuid("reference_id"),
    referenceNumber: text("reference_number"),
    description: text("description"),
    status: text("status").notNull().default("active"),
    createdAt: timestamptz("created_at").notNull(),
    createdBy: uuid("created_by"),
    cancelledAt: timestamptz("cancelled_at"),
    cancelledBy: uuid("cancelled_by"),
    cancellationReferenceId: uuid("cancellation_reference_id"),
    archiveYear: integer("archive_year", { mode: "number" }).notNull(),
    archivedAt: timestamptz("archived_at").notNull().$defaultFn(nowDefault),
  },
);
