// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const licenseActivations = sqliteTable(
  "license_activations",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    licenseId: uuid("license_id").notNull(),
    tenantId: uuid("tenant_id").notNull(),
    serverFingerprint: text("server_fingerprint").notNull(),
    serverFingerprintVersion: integer("server_fingerprint_version", { mode: "number" }).notNull().default(1),
    hostname: text("hostname"),
    appVersion: text("app_version"),
    lastSeenAt: timestamptz("last_seen_at").notNull().$defaultFn(nowDefault),
    deactivatedAt: timestamptz("deactivated_at"),
    deactivationReason: text("deactivation_reason"),
    notes: text("notes"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);

export { licenses as _licensesRef } from "./license.table.js";
