// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, nowDefault } from "../types.js";

export const licenseAuditEvents = sqliteTable(
  "license_audit_events",
  {
    id: integer("id", { mode: "number" }).primaryKey({ autoIncrement: true }),
    licenseId: uuid("license_id"),
    tenantId: uuid("tenant_id"),
    eventType: text("event_type").notNull(),
    payload: jsonb("payload"),
    actor: text("actor"),
    ipAddress: text("ip_address"),
    requestId: text("request_id"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
