// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, textArray, nowDefault, randomUuid } from "../types.js";

export const licenses = sqliteTable(
  "licenses",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    key: text("key").notNull(),
    type: text("type").notNull(),
    status: text("status").notNull().default("active"),
    issuedAt: timestamptz("issued_at").notNull().$defaultFn(nowDefault),
    expiresAt: timestamptz("expires_at"),
    graceDays: integer("grace_days", { mode: "number" }).notNull().default(7),
    maxDevices: integer("max_devices", { mode: "number" }).notNull().default(3),
    features: textArray("features").notNull().default([]),
    vendorId: text("vendor_id"),
    vendorMetadata: jsonb("vendor_metadata"),
    customerName: text("customer_name"),
    customerPhone: text("customer_phone"),
    customerNotes: text("customer_notes"),
    tenantId: uuid("tenant_id"),
    edition: text("edition"),
    plan: text("plan"),
    licenseVersion: text("license_version").notNull().default("v1"),
    productVersion: text("product_version"),
    licenseModel: text("license_model").notNull().default("perpetual"),
    bindingType: text("binding_type"),
    bindingValue: text("binding_value"),
    limits: jsonb("limits").notNull().default({}),
    transferPolicy: jsonb("transfer_policy").notNull().default({"allowed":true,"max_transfers":3,"requires_super_admin":true}),
    updatePolicy: jsonb("update_policy").notNull().default({"channel":"stable","allow_updates":true,"minimum_version":"1.0.0"}),
    backupPolicy: jsonb("backup_policy").notNull().default({"enabled":true,"max_backups":30,"cloud_backup":false}),
    transfersUsed: integer("transfers_used", { mode: "number" }).notNull().default(0),
    offlineToken: text("offline_token"),
    offlineTokenJti: text("offline_token_jti"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
