// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { timestamptz, boolean, nowDefault } from "../types.js";

export const schemaMigrations = sqliteTable(
  "schema_migrations",
  {
    version: text("version").notNull().primaryKey(),
    appliedAt: timestamptz("applied_at").notNull().$defaultFn(nowDefault),
    appliedBy: text("applied_by"),
    description: text("description"),
    checksum: text("checksum"),
    success: boolean("success").notNull().default(true),
  },
);
