// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, boolean, nowDefault, randomUuid } from "../types.js";

export const notifications = sqliteTable(
  "notifications",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    userId: uuid("user_id"),
    title: text("title").notNull(),
    detail: text("detail"),
    kind: text("kind").notNull(),
    severity: text("severity").notNull(),
    targetPath: text("target_path"),
    isRead: boolean("is_read").notNull().default(false),
    isDismissed: boolean("is_dismissed").notNull().default(false),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
