// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, nowDefault, randomUuid } from "../types.js";

export const orders = sqliteTable(
  "orders",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    code: text("code").notNull(),
    customerId: uuid("customer_id"),
    customerNameSnapshot: text("customer_name_snapshot").notNull(),
    customerPhoneSnapshot: text("customer_phone_snapshot"),
    date: date("date").notNull(),
    status: text("status").notNull().default("open"),
    currency: text("currency").notNull().default("SYP"),
    notes: text("notes"),
    fulfilledInvoiceId: uuid("fulfilled_invoice_id"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
