// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, decimalString, randomUuid } from "../types.js";

export const orderItems = sqliteTable(
  "order_items",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    orderId: uuid("order_id").notNull(),
    fabricId: uuid("fabric_id"),
    fabricName: text("fabric_name").notNull(),
    colorId: uuid("color_id"),
    colorName: text("color_name").notNull(),
    colorCode: text("color_code"),
    requestedKg: decimalString("requested_kg", { precision: 12, scale: 2 }).notNull(),
    pieces: integer("pieces", { mode: "number" }).notNull().default(1),
    rollId: uuid("roll_id"),
    widthCm: decimalString("width_cm", { precision: 7, scale: 2 }),
    weightGsm: decimalString("weight_gsm", { precision: 7, scale: 2 }),
    notes: text("notes"),
  },
);
