// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, decimalString, nowDefault, randomUuid } from "../types.js";

export const printJobs = sqliteTable(
  "print_jobs",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    date: date("date").notNull(),
    number: text("number"),
    status: text("status").notNull().default("sent"),
    sourceRollId: uuid("source_roll_id").notNull(),
    sourceFabricId: uuid("source_fabric_id"),
    sourceColorId: uuid("source_color_id"),
    quantityKg: decimalString("quantity_kg", { precision: 12, scale: 2 }).notNull(),
    pieces: integer("pieces", { mode: "number" }).notNull().default(1),
    pressName: text("press_name"),
    printCostPerKg: decimalString("print_cost_per_kg", { precision: 12, scale: 2 }),
    currency: text("currency").notNull().default("SYP"),
    exchangeRate: decimalString("exchange_rate", { precision: 18, scale: 6 }),
    newName: text("new_name"),
    newCategory: text("new_category"),
    newColorName: text("new_color_name"),
    newColorCode: text("new_color_code"),
    newSalePricePerKg: decimalString("new_sale_price_per_kg", { precision: 12, scale: 2 }),
    receivedKg: decimalString("received_kg", { precision: 12, scale: 2 }),
    resultRollId: uuid("result_roll_id"),
    resultFabricId: uuid("result_fabric_id"),
    resultColorId: uuid("result_color_id"),
    receiveNotes: text("receive_notes"),
    receivedAt: timestamptz("received_at"),
    notes: text("notes"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    createdBy: uuid("created_by"),
    customerId: uuid("customer_id"),
    orderId: uuid("order_id"),
    chargePerKg: decimalString("charge_per_kg", { precision: 12, scale: 2 }),
    costExpenseId: uuid("cost_expense_id"),
  },
);
