// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer } from "drizzle-orm/sqlite-core";
import { uuid, decimalString, randomUuid } from "../types.js";

export const returnLines = sqliteTable(
  "return_lines",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    returnId: uuid("return_id").notNull(),
    rollId: uuid("roll_id").notNull(),
    quantityKg: decimalString("quantity_kg", { precision: 12, scale: 2 }).notNull(),
    pieces: integer("pieces", { mode: "number" }).notNull().default(1),
    pricePerKg: decimalString("price_per_kg", { precision: 14, scale: 4 }).notNull(),
  },
);
