// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, numeric, nowDefault, randomUuid } from "../types.js";

export const returns = sqliteTable(
  "returns",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    number: text("number").notNull(),
    kind: text("kind").notNull(),
    date: date("date").notNull(),
    partyId: uuid("party_id").notNull(),
    originalInvoiceId: uuid("original_invoice_id"),
    reason: text("reason").notNull(),
    currency: text("currency").notNull().default("SYP"),
    exchangeRate: numeric("exchange_rate", { precision: 18, scale: 6 }),
    baseTotal: numeric("base_total", { precision: 14, scale: 2 }),
    notesPrint: text("notes_print"),
    notesInternal: text("notes_internal"),
    status: text("status").notNull().default("active"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    createdBy: uuid("created_by"),
    cancelledAt: timestamptz("cancelled_at"),
    cancelledBy: uuid("cancelled_by"),
    clientOperationId: uuid("client_operation_id"),
  },
);
