// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault } from "../types.js";

export const revokedTokens = sqliteTable(
  "revoked_tokens",
  {
    jti: uuid("jti").notNull().primaryKey(),
    subject: uuid("subject"),
    tenantId: uuid("tenant_id"),
    reason: text("reason").notNull(),
    expiresAt: timestamptz("expires_at").notNull(),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
