// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, decimalString, nowDefault, randomUuid } from "../types.js";

export const rolls = sqliteTable(
  "rolls",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    colorId: uuid("color_id").notNull(),
    rollNo: text("roll_no").notNull(),
    dyeBatch: text("dye_batch"),
    initialKg: decimalString("initial_kg", { precision: 12, scale: 2 }).notNull(),
    remainingKg: decimalString("remaining_kg", { precision: 12, scale: 2 }).notNull(),
    pieces: integer("pieces", { mode: "number" }).notNull().default(1),
    remainingPieces: integer("remaining_pieces", { mode: "number" }).notNull().default(0),
    pricePerKg: decimalString("price_per_kg", { precision: 14, scale: 4 }).notNull(),
    salePricePerKg: decimalString("sale_price_per_kg", { precision: 12, scale: 2 }),
    currency: text("currency").notNull().default("SYP"),
    entryPricePerKg: decimalString("entry_price_per_kg", { precision: 14, scale: 4 }),
    entryCurrency: text("entry_currency"),
    entrySource: text("entry_source"),
    entryReference: text("entry_reference"),
    supplierId: uuid("supplier_id"),
    entryDate: date("entry_date").notNull(),
    widthCm: decimalString("width_cm", { precision: 7, scale: 2 }),
    weightGsm: decimalString("weight_gsm", { precision: 7, scale: 2 }),
    status: text("status").notNull().default("in_stock"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
