// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const secrets = sqliteTable(
  "secrets",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id"),
    key: text("key").notNull(),
    ciphertext: text("ciphertext").notNull(),
    iv: text("iv").notNull(),
    authTag: text("auth_tag"),
    algorithm: text("algorithm").notNull().default("aes-256-gcm"),
    version: integer("version", { mode: "number" }).notNull().default(1),
    rotatedAt: timestamptz("rotated_at"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
