// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const serverInstallations = sqliteTable(
  "server_installations",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id"),
    installationId: uuid("installation_id").notNull(),
    hostname: text("hostname"),
    os: text("os"),
    osVersion: text("os_version"),
    appVersion: text("app_version"),
    lastHeartbeatAt: timestamptz("last_heartbeat_at"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
