// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, nowDefault, randomUuid } from "../types.js";

export const settings = sqliteTable(
  "settings",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    company: jsonb("company").default({}),
    currencies: jsonb("currencies").default([]),
    paymentMethods: jsonb("payment_methods").default([]),
    taxes: jsonb("taxes").default([]),
    units: jsonb("units").default([]),
    warehouses: jsonb("warehouses").default([]),
    printing: jsonb("printing").default({}),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
