// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, boolean, textArray, nowDefault } from "../types.js";

export const setupWizardState = sqliteTable(
  "setup_wizard_state",
  {
    tenantId: uuid("tenant_id").notNull().primaryKey(),
    currentStep: text("current_step").notNull().default("welcome"),
    completedSteps: textArray("completed_steps").notNull().default([]),
    isCompleted: boolean("is_completed").notNull().default(false),
    completedAt: timestamptz("completed_at"),
    data: jsonb("data").default({}),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
