// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, date, decimalString, nowDefault, randomUuid } from "../types.js";

export const stockMovements = sqliteTable(
  "stock_movements",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    rollId: uuid("roll_id").notNull(),
    direction: text("direction").notNull(),
    movementType: text("movement_type").notNull(),
    quantityKg: decimalString("quantity_kg", { precision: 12, scale: 2 }).notNull(),
    balanceAfterKg: decimalString("balance_after_kg", { precision: 12, scale: 2 }).notNull(),
    referenceType: text("reference_type"),
    referenceId: uuid("reference_id"),
    referenceNumber: text("reference_number"),
    movementDate: date("movement_date").notNull(),
    description: text("description"),
    status: text("status").notNull().default("active"),
    createdBy: uuid("created_by"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
);
