// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, decimalString, nowDefault, randomUuid } from "../types.js";

export const syncResourceClaims = sqliteTable(
  "sync_resource_claims",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    resourceType: text("resource_type").notNull(),
    resourceId: uuid("resource_id").notNull(),
    quantityKg: decimalString("quantity_kg", { precision: 14, scale: 3 }),
    quantityPieces: integer("quantity_pieces", { mode: "number" }),
    claimedByOpId: uuid("claimed_by_op_id").notNull(),
    claimedByDeviceId: uuid("claimed_by_device_id"),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id").notNull(),
    claimedAt: timestamptz("claimed_at").notNull().$defaultFn(nowDefault),
  },
);
