// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, nowDefault, randomUuid } from "../types.js";
import { nextSequenceValue } from "../sequences.js";

export const syncOutbox = sqliteTable(
  "sync_outbox",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    syncDeviceId: uuid("sync_device_id"),
    opId: uuid("op_id").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id").notNull(),
    operation: text("operation").notNull(),
    payload: jsonb("payload").notNull().$type<Record<string, unknown>>(),
    status: text("status").notNull().default("pending"),
    errorDetail: text("error_detail"),
    seq: integer("seq", { mode: "number" }).notNull().$defaultFn(() => nextSequenceValue("sync_outbox_seq_seq")),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
    syncedAt: timestamptz("synced_at"),
    leaseOwner: text("lease_owner"),
    leaseToken: uuid("lease_token"),
    leaseUntil: timestamptz("lease_until"),
    claimedAt: timestamptz("claimed_at"),
  },
);
