// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, uuidArray, nowDefault, randomUuid } from "../types.js";

export const syncDevices = sqliteTable(
  "sync_devices",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    deviceRegistrationId: uuid("device_registration_id"),
    lastSeenByUserId: uuid("last_seen_by_user_id"),
    authorizedUserIds: uuidArray("authorized_user_ids").notNull().default([]),
    revokedAt: timestamptz("revoked_at"),
    revokeReason: text("revoke_reason"),
    deviceFingerprint: text("device_fingerprint").notNull(),
    deviceFingerprintVersion: integer("device_fingerprint_version", { mode: "number" }).notNull().default(1),
    platform: text("platform").notNull(),
    hostname: text("hostname"),
    label: text("label"),
    lastSeenAt: timestamptz("last_seen_at").notNull().$defaultFn(nowDefault),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
