// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault } from "../types.js";

export const syncState = sqliteTable(
  "sync_state",
  {
    tenantId: uuid("tenant_id").notNull().primaryKey(),
    lastPullAt: timestamptz("last_pull_at"),
    lastPullSeq: integer("last_pull_seq", { mode: "number" }),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
