// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, nowDefault, randomUuid } from "../types.js";
import { nextSequenceValue } from "../sequences.js";

export const syncInbox = sqliteTable(
  "sync_inbox",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    syncDeviceId: uuid("sync_device_id"),
    opId: uuid("op_id").notNull(),
    entityType: text("entity_type").notNull(),
    entityId: uuid("entity_id").notNull(),
    operation: text("operation").notNull(),
    payload: jsonb("payload").notNull().$type<Record<string, unknown>>(),
    status: text("status").notNull().default("received"),
    rejectReason: text("reject_reason"),
    conflictOpId: uuid("conflict_op_id"),
    conflictDetail: jsonb("conflict_detail").$type<Record<string, unknown>>(),
    materializeError: jsonb("materialize_error").$type<Record<string, unknown>>(),
    applyAttempts: integer("apply_attempts", { mode: "number" }).notNull().default(0),
    lastAttemptAt: timestamptz("last_attempt_at"),
    receivedSeq: integer("received_seq", { mode: "number" }).notNull().$defaultFn(() => nextSequenceValue("sync_inbox_received_seq_seq")),
    receivedAt: timestamptz("received_at").notNull().$defaultFn(nowDefault),
    appliedAt: timestamptz("applied_at"),
    appliedSeq: integer("applied_seq", { mode: "number" }),
  },
);
