// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, primaryKey } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault } from "../types.js";

export const syncDeviceAuthorizedUsers = sqliteTable(
  "sync_device_authorized_users",
  {
    deviceId: uuid("device_id").notNull(),
    userId: uuid("user_id").notNull(),
    tenantId: uuid("tenant_id").notNull(),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
  },
  (t) => [primaryKey({ columns: [t.deviceId, t.userId] })],
);
