// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, nowDefault, randomUuid } from "../types.js";

export const systemAdmins = sqliteTable(
  "system_admins",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    name: text("name"),
    role: text("role").notNull().default("super_admin"),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
