// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, textArray, nowDefault, randomUuid } from "../types.js";

export const tenants = sqliteTable(
  "tenants",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    status: text("status").notNull().default("active"),
    maxUsers: integer("max_users", { mode: "number" }).notNull().default(5),
    ownerUserId: uuid("owner_user_id"),
    licenseKey: text("license_key"),
    licenseExpiresAt: timestamptz("license_expires_at"),
    settings: jsonb("settings").default({}),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
    licenseStatus: text("license_status").notNull().default("trial"),
    licenseType: text("license_type").notNull().default("trial"),
    maxDevices: integer("max_devices", { mode: "number" }).notNull().default(3),
    activationId: uuid("activation_id"),
    serverFingerprint: text("server_fingerprint"),
    lastHeartbeatAt: timestamptz("last_heartbeat_at"),
    licenseEdition: text("license_edition"),
    licensePlan: text("license_plan"),
    licenseVersion: text("license_version").notNull().default("v1"),
    productVersion: text("product_version"),
    licenseModel: text("license_model").notNull().default("perpetual"),
    licenseFeatures: textArray("license_features").notNull().default([]),
    licenseLimits: jsonb("license_limits").notNull().default({}),
    licenseBindingType: text("license_binding_type"),
    licenseBindingValue: text("license_binding_value"),
    transferPolicy: jsonb("transfer_policy").notNull().default({}),
    updatePolicy: jsonb("update_policy").notNull().default({}),
    backupPolicy: jsonb("backup_policy").notNull().default({}),
    transfersUsed: integer("transfers_used", { mode: "number" }).notNull().default(0),
  },
);
