// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, boolean, nowDefault, randomUuid } from "../types.js";

export const users = sqliteTable(
  "users",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    pinHash: text("pin_hash"),
    role: text("role").notNull(),
    isLicenseOwner: boolean("is_license_owner").notNull().default(false),
    active: boolean("active").notNull().default(true),
    tokensRevokedBefore: timestamptz("tokens_revoked_before"),
    permissions: jsonb("permissions").default([]),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
