// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, jsonb, date, numeric, nowDefault, randomUuid } from "../types.js";

export const vouchers = sqliteTable(
  "vouchers",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    kind: text("kind").notNull(),
    number: text("number").notNull(),
    date: date("date").notNull(),
    partyId: uuid("party_id").notNull(),
    partyKind: text("party_kind").notNull(),
    invoiceId: uuid("invoice_id"),
    amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
    discount: numeric("discount", { precision: 14, scale: 2 }).notNull().default(0),
    currency: text("currency").notNull().default("SYP"),
    appliedAmount: numeric("applied_amount", { precision: 14, scale: 2 }),
    exchangeRate: numeric("exchange_rate", { precision: 18, scale: 6 }),
    baseAmount: numeric("base_amount", { precision: 14, scale: 2 }),
    method: text("method").notNull(),
    status: text("status").notNull().default("active"),
    notesPrint: text("notes_print"),
    notesInternal: text("notes_internal"),
    attachments: jsonb("attachments").default([]),
    version: integer("version", { mode: "number" }).notNull().default(1),
    createdAt: timestamptz("created_at").notNull().$defaultFn(nowDefault),
    createdBy: uuid("created_by"),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
    cancelledAt: timestamptz("cancelled_at"),
    cancelledBy: uuid("cancelled_by"),
    clientOperationId: uuid("client_operation_id"),
  },
);
