// GENERATED by scripts/generate-sqlite-schema.mts from the PG Drizzle schema and the live
// schema fingerprint (specs/001-desktop-sqlite-engine T034). Do not edit by hand.
import { sqliteTable, integer, text } from "drizzle-orm/sqlite-core";
import { uuid, timestamptz, numeric, nowDefault, randomUuid } from "../types.js";

export const yearlyPartySummaries = sqliteTable(
  "yearly_party_summaries",
  {
    id: uuid("id").notNull().primaryKey().$defaultFn(randomUuid),
    tenantId: uuid("tenant_id").notNull(),
    partyId: uuid("party_id").notNull(),
    year: integer("year", { mode: "number" }).notNull(),
    currency: text("currency").notNull().default("SYP"),
    openingBalance: numeric("opening_balance", { precision: 14, scale: 2 }).notNull().default(0),
    closingBalance: numeric("closing_balance", { precision: 14, scale: 2 }).notNull().default(0),
    totalDebit: numeric("total_debit", { precision: 14, scale: 2 }).notNull().default(0),
    totalCredit: numeric("total_credit", { precision: 14, scale: 2 }).notNull().default(0),
    invoiceCount: integer("invoice_count", { mode: "number" }).notNull().default(0),
    voucherCount: integer("voucher_count", { mode: "number" }).notNull().default(0),
    generatedAt: timestamptz("generated_at").notNull().$defaultFn(nowDefault),
    updatedAt: timestamptz("updated_at").notNull().$defaultFn(nowDefault),
  },
);
