import {
  pgTable,
  uuid,
  varchar,
  timestamp,
  integer,
  decimal,
  bigint,
  real,
  text,
  boolean,
  jsonb,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { tenants } from "./tenant.table.js";

export const parties = pgTable(
  "parties",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id),
    kind: varchar("kind", { length: 10 }).notNull(),
    code: varchar("code", { length: 50 }),
    name: varchar("name", { length: 255 }).notNull(),
    companyName: varchar("company_name", { length: 255 }),
    commercialReg: varchar("commercial_reg", { length: 100 }),
    category: varchar("category", { length: 100 }),
    salesRep: varchar("sales_rep", { length: 100 }),
    phone: varchar("phone", { length: 30 }),
    mobile: varchar("mobile", { length: 30 }),
    whatsapp: varchar("whatsapp", { length: 30 }),
    altPhone: varchar("alt_phone", { length: 30 }),
    email: varchar("email", { length: 320 }),
    website: varchar("website", { length: 500 }),
    address: text("address"),
    city: varchar("city", { length: 100 }),
    country: varchar("country", { length: 100 }),
    taxNumber: varchar("tax_number", { length: 100 }),
    openingBalance: real("opening_balance").notNull().default(0),
    creditLimit: real("credit_limit").default(0),
    currency: varchar("currency", { length: 3 }).notNull().default("SYP"),
    paymentTerms: varchar("payment_terms", { length: 20 }),
    paymentMethod: varchar("payment_method", { length: 20 }),
    defaultDiscount: bigint("default_discount_amount", { mode: "number" }).default(0),
    vat: decimal("vat", { precision: 5, scale: 4 }).default("0"),
    status: varchar("status", { length: 20 }).notNull().default("active"),
    notes: text("notes"),
    attachments: jsonb("attachments").default("[]"),
    version: integer("version").notNull().default(1),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid("created_by"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    cancelledBy: uuid("cancelled_by"),
  },
  (table) => ({
    tenantCodeIdx: uniqueIndex("idx_parties_tenant_code").on(table.tenantId, table.code),
    tenantNameIdx: uniqueIndex("idx_parties_tenant_name").on(table.tenantId, table.name),
  }),
);
