/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashboxRouteImport } from './routes/cashbox'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrintCenterRouteImport } from './routes/print-center'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as ExpensesNewRouteImport } from './routes/expenses.new'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as InvoicesTrackingRouteImport } from './routes/invoices.tracking'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrdersNewRouteImport } from './routes/orders.new'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsNewRouteImport } from './routes/payments.new'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts.index'
import { Route as ReceiptsNewRouteImport } from './routes/receipts.new'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'
import { Route as ReturnsIndexRouteImport } from './routes/returns.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsActivityRouteImport } from './routes/settings.activity'
import { Route as SettingsAuditRouteImport } from './routes/settings.audit'
import { Route as SettingsBackupRouteImport } from './routes/settings.backup'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SettingsCurrenciesRouteImport } from './routes/settings.currencies'
import { Route as SettingsInvoiceRouteImport } from './routes/settings.invoice'
import { Route as SettingsPaymentMethodsRouteImport } from './routes/settings.payment-methods'
import { Route as SettingsPrintingRouteImport } from './routes/settings.printing'
import { Route as SettingsTaxesRouteImport } from './routes/settings.taxes'
import { Route as SettingsUnitsRouteImport } from './routes/settings.units'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsWarehousesRouteImport } from './routes/settings.warehouses'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as InvoicesEntryNewRouteImport } from './routes/invoices.entry.new'
import { Route as InvoicesPrintReceiveNewRouteImport } from './routes/invoices.print-receive.new'
import { Route as InvoicesPrintSendNewRouteImport } from './routes/invoices.print-send.new'
import { Route as InvoicesSaleNewRouteImport } from './routes/invoices.sale.new'
import { Route as ReturnsEntryNewRouteImport } from './routes/returns.entry.new'
import { Route as ReturnsSaleNewRouteImport } from './routes/returns.sale.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashboxRoute = CashboxRouteImport.update({
  id: '/cashbox',
  path: '/cashbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCenterRoute = PrintCenterRouteImport.update({
  id: '/print-center',
  path: '/print-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesTrackingRoute = InvoicesTrackingRouteImport.update({
  id: '/invoices/tracking',
  path: '/invoices/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsNewRoute = PaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsNewRoute = ReceiptsNewRouteImport.update({
  id: '/receipts/new',
  path: '/receipts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReportsRoute,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsActivityRoute = SettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCurrenciesRoute = SettingsCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsInvoiceRoute = SettingsInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPaymentMethodsRoute = SettingsPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrintingRoute = SettingsPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTaxesRoute = SettingsTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUnitsRoute = SettingsUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWarehousesRoute = SettingsWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => SettingsRoute,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesEntryNewRoute = InvoicesEntryNewRouteImport.update({
  id: '/invoices/entry/new',
  path: '/invoices/entry/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPrintReceiveNewRoute = InvoicesPrintReceiveNewRouteImport.update({
  id: '/invoices/print-receive/new',
  path: '/invoices/print-receive/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPrintSendNewRoute = InvoicesPrintSendNewRouteImport.update({
  id: '/invoices/print-send/new',
  path: '/invoices/print-send/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesSaleNewRoute = InvoicesSaleNewRouteImport.update({
  id: '/invoices/sale/new',
  path: '/invoices/sale/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsEntryNewRoute = ReturnsEntryNewRouteImport.update({
  id: '/returns/entry/new',
  path: '/returns/entry/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsSaleNewRoute = ReturnsSaleNewRouteImport.update({
  id: '/returns/sale/new',
  path: '/returns/sale/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/inventory': typeof InventoryRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/print-center': typeof PrintCenterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/tracking': typeof InvoicesTrackingRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/settings/activity': typeof SettingsActivityRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/invoice': typeof SettingsInvoiceRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/printing': typeof SettingsPrintingRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/units': typeof SettingsUnitsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/warehouses': typeof SettingsWarehousesRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/invoices/entry/new': typeof InvoicesEntryNewRoute
  '/invoices/print-receive/new': typeof InvoicesPrintReceiveNewRoute
  '/invoices/print-send/new': typeof InvoicesPrintSendNewRoute
  '/invoices/sale/new': typeof InvoicesSaleNewRoute
  '/returns/entry/new': typeof ReturnsEntryNewRoute
  '/returns/sale/new': typeof ReturnsSaleNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/inventory': typeof InventoryRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/print-center': typeof PrintCenterRoute
  '/customers/$id': typeof CustomersIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/tracking': typeof InvoicesTrackingRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/settings/activity': typeof SettingsActivityRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/invoice': typeof SettingsInvoiceRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/printing': typeof SettingsPrintingRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/units': typeof SettingsUnitsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/warehouses': typeof SettingsWarehousesRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers': typeof CustomersIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/invoices/entry/new': typeof InvoicesEntryNewRoute
  '/invoices/print-receive/new': typeof InvoicesPrintReceiveNewRoute
  '/invoices/print-send/new': typeof InvoicesPrintSendNewRoute
  '/invoices/sale/new': typeof InvoicesSaleNewRoute
  '/returns/entry/new': typeof ReturnsEntryNewRoute
  '/returns/sale/new': typeof ReturnsSaleNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/inventory': typeof InventoryRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/print-center': typeof PrintCenterRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/tracking': typeof InvoicesTrackingRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/receipts/new': typeof ReceiptsNewRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/settings/activity': typeof SettingsActivityRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/currencies': typeof SettingsCurrenciesRoute
  '/settings/invoice': typeof SettingsInvoiceRoute
  '/settings/payment-methods': typeof SettingsPaymentMethodsRoute
  '/settings/printing': typeof SettingsPrintingRoute
  '/settings/taxes': typeof SettingsTaxesRoute
  '/settings/units': typeof SettingsUnitsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/warehouses': typeof SettingsWarehousesRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/invoices/entry/new': typeof InvoicesEntryNewRoute
  '/invoices/print-receive/new': typeof InvoicesPrintReceiveNewRoute
  '/invoices/print-send/new': typeof InvoicesPrintSendNewRoute
  '/invoices/sale/new': typeof InvoicesSaleNewRoute
  '/returns/entry/new': typeof ReturnsEntryNewRoute
  '/returns/sale/new': typeof ReturnsSaleNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashbox'
    | '/inventory'
    | '/ledger'
    | '/login'
    | '/print-center'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/tracking'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/new'
    | '/receipts/new'
    | '/reports/$slug'
    | '/settings/activity'
    | '/settings/audit'
    | '/settings/backup'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/invoice'
    | '/settings/payment-methods'
    | '/settings/printing'
    | '/settings/taxes'
    | '/settings/units'
    | '/settings/users'
    | '/settings/warehouses'
    | '/suppliers/$id'
    | '/customers/'
    | '/expenses/'
    | '/invoices/'
    | '/orders/'
    | '/payments/'
    | '/receipts/'
    | '/reports/'
    | '/returns/'
    | '/settings/'
    | '/suppliers/'
    | '/invoices/entry/new'
    | '/invoices/print-receive/new'
    | '/invoices/print-send/new'
    | '/invoices/sale/new'
    | '/returns/entry/new'
    | '/returns/sale/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashbox'
    | '/inventory'
    | '/ledger'
    | '/login'
    | '/print-center'
    | '/customers/$id'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/tracking'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/new'
    | '/receipts/new'
    | '/reports/$slug'
    | '/settings/activity'
    | '/settings/audit'
    | '/settings/backup'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/invoice'
    | '/settings/payment-methods'
    | '/settings/printing'
    | '/settings/taxes'
    | '/settings/units'
    | '/settings/users'
    | '/settings/warehouses'
    | '/suppliers/$id'
    | '/customers'
    | '/expenses'
    | '/invoices'
    | '/orders'
    | '/payments'
    | '/receipts'
    | '/reports'
    | '/returns'
    | '/settings'
    | '/suppliers'
    | '/invoices/entry/new'
    | '/invoices/print-receive/new'
    | '/invoices/print-send/new'
    | '/invoices/sale/new'
    | '/returns/entry/new'
    | '/returns/sale/new'
  id:
    | '__root__'
    | '/'
    | '/cashbox'
    | '/inventory'
    | '/ledger'
    | '/login'
    | '/print-center'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/expenses/new'
    | '/invoices/$id'
    | '/invoices/tracking'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/new'
    | '/receipts/new'
    | '/reports/$slug'
    | '/settings/activity'
    | '/settings/audit'
    | '/settings/backup'
    | '/settings/company'
    | '/settings/currencies'
    | '/settings/invoice'
    | '/settings/payment-methods'
    | '/settings/printing'
    | '/settings/taxes'
    | '/settings/units'
    | '/settings/users'
    | '/settings/warehouses'
    | '/suppliers/$id'
    | '/customers/'
    | '/expenses/'
    | '/invoices/'
    | '/orders/'
    | '/payments/'
    | '/receipts/'
    | '/reports/'
    | '/returns/'
    | '/settings/'
    | '/suppliers/'
    | '/invoices/entry/new'
    | '/invoices/print-receive/new'
    | '/invoices/print-send/new'
    | '/invoices/sale/new'
    | '/returns/entry/new'
    | '/returns/sale/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashboxRoute: typeof CashboxRoute
  InventoryRoute: typeof InventoryRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  PrintCenterRoute: typeof PrintCenterRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  CustomersIdRoute: typeof CustomersIdRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesTrackingRoute: typeof InvoicesTrackingRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  PaymentsNewRoute: typeof PaymentsNewRoute
  ReceiptsNewRoute: typeof ReceiptsNewRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  ReturnsIndexRoute: typeof ReturnsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  InvoicesEntryNewRoute: typeof InvoicesEntryNewRoute
  InvoicesPrintReceiveNewRoute: typeof InvoicesPrintReceiveNewRoute
  InvoicesPrintSendNewRoute: typeof InvoicesPrintSendNewRoute
  InvoicesSaleNewRoute: typeof InvoicesSaleNewRoute
  ReturnsEntryNewRoute: typeof ReturnsEntryNewRoute
  ReturnsSaleNewRoute: typeof ReturnsSaleNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbox': {
      id: '/cashbox'
      path: '/cashbox'
      fullPath: '/cashbox'
      preLoaderRoute: typeof CashboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-center': {
      id: '/print-center'
      path: '/print-center'
      fullPath: '/print-center'
      preLoaderRoute: typeof PrintCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/tracking': {
      id: '/invoices/tracking'
      path: '/invoices/tracking'
      fullPath: '/invoices/tracking'
      preLoaderRoute: typeof InvoicesTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/new': {
      id: '/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof PaymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/new': {
      id: '/receipts/new'
      path: '/receipts/new'
      fullPath: '/receipts/new'
      preLoaderRoute: typeof ReceiptsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/activity': {
      id: '/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof SettingsActivityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/currencies': {
      id: '/settings/currencies'
      path: '/currencies'
      fullPath: '/settings/currencies'
      preLoaderRoute: typeof SettingsCurrenciesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/invoice': {
      id: '/settings/invoice'
      path: '/invoice'
      fullPath: '/settings/invoice'
      preLoaderRoute: typeof SettingsInvoiceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/payment-methods': {
      id: '/settings/payment-methods'
      path: '/payment-methods'
      fullPath: '/settings/payment-methods'
      preLoaderRoute: typeof SettingsPaymentMethodsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/printing': {
      id: '/settings/printing'
      path: '/printing'
      fullPath: '/settings/printing'
      preLoaderRoute: typeof SettingsPrintingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/taxes': {
      id: '/settings/taxes'
      path: '/taxes'
      fullPath: '/settings/taxes'
      preLoaderRoute: typeof SettingsTaxesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/units': {
      id: '/settings/units'
      path: '/units'
      fullPath: '/settings/units'
      preLoaderRoute: typeof SettingsUnitsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/warehouses': {
      id: '/settings/warehouses'
      path: '/warehouses'
      fullPath: '/settings/warehouses'
      preLoaderRoute: typeof SettingsWarehousesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/entry/new': {
      id: '/invoices/entry/new'
      path: '/invoices/entry/new'
      fullPath: '/invoices/entry/new'
      preLoaderRoute: typeof InvoicesEntryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/print-receive/new': {
      id: '/invoices/print-receive/new'
      path: '/invoices/print-receive/new'
      fullPath: '/invoices/print-receive/new'
      preLoaderRoute: typeof InvoicesPrintReceiveNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/print-send/new': {
      id: '/invoices/print-send/new'
      path: '/invoices/print-send/new'
      fullPath: '/invoices/print-send/new'
      preLoaderRoute: typeof InvoicesPrintSendNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/sale/new': {
      id: '/invoices/sale/new'
      path: '/invoices/sale/new'
      fullPath: '/invoices/sale/new'
      preLoaderRoute: typeof InvoicesSaleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/entry/new': {
      id: '/returns/entry/new'
      path: '/returns/entry/new'
      fullPath: '/returns/entry/new'
      preLoaderRoute: typeof ReturnsEntryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/sale/new': {
      id: '/returns/sale/new'
      path: '/returns/sale/new'
      fullPath: '/returns/sale/new'
      preLoaderRoute: typeof ReturnsSaleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsSlugRoute: typeof ReportsSlugRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsSlugRoute: ReportsSlugRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SettingsRouteChildren {
  SettingsActivityRoute: typeof SettingsActivityRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsCurrenciesRoute: typeof SettingsCurrenciesRoute
  SettingsInvoiceRoute: typeof SettingsInvoiceRoute
  SettingsPaymentMethodsRoute: typeof SettingsPaymentMethodsRoute
  SettingsPrintingRoute: typeof SettingsPrintingRoute
  SettingsTaxesRoute: typeof SettingsTaxesRoute
  SettingsUnitsRoute: typeof SettingsUnitsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsWarehousesRoute: typeof SettingsWarehousesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsActivityRoute: SettingsActivityRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsCurrenciesRoute: SettingsCurrenciesRoute,
  SettingsInvoiceRoute: SettingsInvoiceRoute,
  SettingsPaymentMethodsRoute: SettingsPaymentMethodsRoute,
  SettingsPrintingRoute: SettingsPrintingRoute,
  SettingsTaxesRoute: SettingsTaxesRoute,
  SettingsUnitsRoute: SettingsUnitsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsWarehousesRoute: SettingsWarehousesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashboxRoute: CashboxRoute,
  InventoryRoute: InventoryRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  PrintCenterRoute: PrintCenterRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  CustomersIdRoute: CustomersIdRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesTrackingRoute: InvoicesTrackingRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  PaymentsNewRoute: PaymentsNewRoute,
  ReceiptsNewRoute: ReceiptsNewRoute,
  SuppliersIdRoute: SuppliersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  ReturnsIndexRoute: ReturnsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  InvoicesEntryNewRoute: InvoicesEntryNewRoute,
  InvoicesPrintReceiveNewRoute: InvoicesPrintReceiveNewRoute,
  InvoicesPrintSendNewRoute: InvoicesPrintSendNewRoute,
  InvoicesSaleNewRoute: InvoicesSaleNewRoute,
  ReturnsEntryNewRoute: ReturnsEntryNewRoute,
  ReturnsSaleNewRoute: ReturnsSaleNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
